#added prometheus target to the existing otel-collector-config

  prometheus:
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
        # otel-collector internal metrics
        - job_name: otel-collector
          static_configs:
          - targets:
              - localhost:8888
            labels:
              job_name: otel-collector
#scrapping prometheus metrics
        - job_name: "prometheus-receiver"
          scrape_interval: 5s
          static_configs:
            - targets: ["192.168.231.128:8333"]